apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  labels:
    app: notification-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: notification-service
