apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: default
  labels:
    app: notification-service
type: Opaque
data:
  SERVICE_NAME: bm90aWZpY2F0aW9uLXNlcnZpY2U=
  DB_USER: YWRtaW4=
  DB_PASS: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
  amazonProperties.accessKey: "VVU1MUJSWVFSOEpKSkQyWDBTMTE="
  amazonProperties.secretKey: "aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA=="
  AWS_ACCESS_KEY: "VVU1MUJSWVFSOEpKSkQyWDBTMTE="
  AWS_SECRET_KEY: "aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA=="
  amazonProperties.assetsSecretKey: "aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA=="
  amazonProperties.assetsAccessKey: "VVU1MUJSWVFSOEpKSkQyWDBTMTE="
  spring.mail.userName: "bm8tcmVwbHlAZmF6ZWFsLmNvbQ=="
  spring.mail.password: "TmF6bzEwOTQj"
