apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: events-service-pdb
  labels:
    app: events-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: events-service
