apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: default
  labels:
    app: events-service
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    app: events-service
