---
- name: Deploy Services (No Vault)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    env: "{{ env | default('dev') }}"
    services:
      - config-server
      - api-server
      - site-management-service
      - shopping-service
      - posts-service
      - payment-gateway
      - order-service
      - notification-service
      - loyalty-service
      - inventory-service
      - fazeal-business-management
      - fazeal-business
      - events-service
      - angular-customer-ssr
      - cron-jobs
      - chat-app
      - business-chat
      - api-gateway
      - angular-dev
      - angular-customer
      - angular-business
      - angular-ads
      - angular-employee
      - album-service
      - ads-service
      - promotion-service
      - catalog-service
      - customer-service
      - employees-service
      - payment-service
      - translation-service
      - watermark-detection

  tasks:
    - name: Deploy ConfigMaps
      kubernetes.core.k8s:
        state: present
        src: "application_deployment/{{ env }}/{{ item }}/configmap.yml"
      loop: "{{ services }}"
      delegate_to: localhost
      run_once: true

    - name: Deploy Secrets
      kubernetes.core.k8s:
        state: present
        src: "application_deployment/{{ env }}/{{ item }}/secret.yml"
      loop: "{{ services }}"
      delegate_to: localhost
      run_once: true

    - name: Deploy Services
      kubernetes.core.k8s:
        state: present
        src: "application_deployment/{{ env }}/{{ item }}/service.yml"
      loop: "{{ services }}"
      delegate_to: localhost
      run_once: true

    - name: Deploy Deployments
      kubernetes.core.k8s:
        state: present
        src: "application_deployment/{{ env }}/{{ item }}/deployment.yml"
      loop: "{{ services }}"
      delegate_to: localhost
      run_once: true 