---
- name: Pre-flight checks
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if env variable is defined
      fail:
        msg: "The 'env' variable is not defined. Please pass it as an extra var, e.g., -e 'env=dev'"
      when: env is not defined

- import_playbook: deploy-elastic-stack.yml
- import_playbook: deploy-ingress.yml
- import_playbook: deploy-dataload-service.yml

- name: Deploy All Applications to the MicroK8s Cluster
  hosts: localhost
  gather_facts: no

  # Load the service definitions. The 'services' variable will be a list.
  vars_files:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    - "cluster_vars/{{ env }}.yml"
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
    - "group_vars/{{ env }}/main.yml"
    - vars/services.yml
    - group_vars/all/main.yml
    - group_vars/all/vault.yml

  tasks:
    - name: Create Docker Hub secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dockerhub-secret
            namespace: "{{ app.namespace | default('default') }}"
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ dockerhub_secret_json | b64encode }}"
      run_once: true

    - name: "Deploying service: {{ item.name }}"
      include_role:
        name: app_deployer
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      vars:
        app: "{{ item }}"
      loop: "{{ services }}"
=======
=======
>>>>>>> Stashed changes
      # Loop over the list of services and pass the dictionary as a variable
      loop: "{{ services }}"
      # The 'app' variable will hold the service-specific data for the role
      vars:
<<<<<<< Updated upstream
        app: "{{ item }}"
>>>>>>> Stashed changes
=======
        app: "{{ item }}"
>>>>>>> Stashed changes
