---
- name: Deploy a Sample Application to the MicroK8s Cluster
  hosts: localhost
  gather_facts: no

  vars:
    # --- Override the default variables from the 'app_deployer' role here ---

    # Application-specific settings
    app_name: "nginx-web"
    app_namespace: "production"
    app_image: "nginx:1.21"
    app_replicas: 2
    app_container_port: 80

    # Configuration for the ConfigMap
    app_config:
      NGINX_HOST: "nginx-web.fazeal.com"
      NGINX_PORT: "80"

    # Sensitive data for the Secret (use Ansible Vault in production)
    app_secrets:
      API_KEY: "supersecretkey"

    # Define resource limits for this specific application
    app_resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"

    # HPA settings for the NGINX app
    app_hpa:
      min_replicas: 2
      max_replicas: 10
      cpu_utilization: 75 # Custom CPU target for this app

    # Ingress settings
    app_ingress_hostname: "nginx-web.fazeal.com"

    # For this app, we want all standard manifests
    enabled_manifests:
      - configmap.yml
      - secret.yml
      - deployment.yml
      - service.yml
      - hpa.yml
      - ingress.yml

  roles:
    - role: app_deployer
