---
- name: Deploy NGINX Ingress Controller
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Apply Ingress manifests
      k8s:
        state: present
        src: "ingress/{{ item }}"
      loop:
        - 01-namespace.yml
        - 02-service-account-controller.yml
        - 03-service-account-admission.yml
        - 04-role-controller.yml
        - 05-role-admission.yml
        - 06-cluster-role-controller.yml
        - 07-cluster-role-admission.yml
        - 08-role-binding-controller.yml
        - 09-role-binding-admission.yml
        - 10-cluster-role-binding-controller.yml
        - 11-cluster-role-binding-admission.yml
        - 12-configmap.yml
        - 13-service-controller.yml
        - 14-service-admission.yml
        - 15-deployment.yml
        - 16-job-admission-create.yml
        - 17-job-admission-patch.yml
        - 18-ingress-class.yml
<<<<<<< Updated upstream
        - 19-validating-webhook.yml
=======
        - 19-validating-webhook.yml
        - 20-ingress.yml
>>>>>>> Stashed changes
