---
- name: Install MicroK8s Cluster
  hosts: localhost
  gather_facts: no

  vars_files:
    - "cluster_vars/{{ env }}.yml"

  tasks:
    - name: Generate hosts file from template
      template:
        src: hosts.j2
        dest: hosts

- name: Clean up existing MicroK8s installation
  hosts: kube_cluster
  become: yes
  roles:
    - role: microk8s_cleanup

- name: Install MicroK8s on all nodes
  hosts: kube_cluster
  become: yes
  roles:
    - role: microk8s_install

- name: Initialize MicroK8s cluster on the primary master
  hosts: kube_masters[0]
  become: yes
  roles:
    - role: microk8s_master

- name: Join worker nodes to the cluster
  hosts: kube_workers
  become: yes
  roles:
    - role: microk8s_worker
