apiVersion: v1
kind: Service
metadata:
  name: fazeal-business-management
  namespace: default
  labels:
    app: fazeal-business-management
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
      name: http
  selector:
    app: fazeal-business-management
