apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-jobs
  namespace: default
  labels:
    app: cron-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-jobs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: cron-jobs
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: cron-jobs
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8011
              name: http
              protocol: TCP
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: SERVICE_NAME
            - name: NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: NAMESPACE
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: LOG_LEVEL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: DB_HOST
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: spring.profiles.active
            - name: loyalty-service-api.base
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: loyalty-service-api.base
            - name: events-api.base
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: events-api.base
            - name: posts-service.base
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: posts-service.base
            - name: fazeal-business-admin-service-api.base
              valueFrom:
                configMapKeyRef:
                  name: cron-jobs-config
                  key: fazeal-business-admin-service-api.base
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cron-jobs-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cron-jobs-secret
                  key: DB_PASSWORD
          startupProbe:
            tcpSocket:
              port: 8011
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60   # ~5 min warmup
          readinessProbe:
            tcpSocket:
              port: 8011
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8011
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"