apiVersion: v1
kind: Service
metadata:
  name: cron-jobs
  namespace: default
  labels:
    app: cron-jobs
spec:
  type: ClusterIP
  ports:
    - port: 8011
      targetPort: 8011
      protocol: TCP
      name: http
  selector:
    app: cron-jobs