apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: default
  labels:
    app: api-gateway
data:
  SERVICE_NAME: "api-gateway"
  NAMESPACE: "default"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
  DISCOVERY_URL: "http://192.168.1.212:8761"
  eureka.instance.ip-address: "api-gateway"
  eureka.instance.prefer-ip-address: "true"
  server.port: "80"
