apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  labels:
    app: api-gateway
    component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
