apiVersion: v1
kind: Service
metadata:
  name: angular-dev
  namespace: default
  labels:
    app: angular-dev
spec:
  type: ClusterIP
  ports:
    - port: 4204
      targetPort: 4204
      protocol: TCP
      name: http
  selector:
    app: angular-dev
