apiVersion: v1
kind: Service
metadata:
  name: angular-dev
  namespace: default
  labels:
    app: angular-dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4000      
      targetPort: 4000  
      protocol: TCP
  selector:
    app: angular-dev