apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: default
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
    k8s.io/ingress-nginx: nginx