apiVersion: v1
kind: ConfigMap
metadata:
  name: business-chat-config
  namespace: default
  labels:
    app: business-chat
data:
  SERVICE_NAME: "business-chat"
  NAMESPACE: "default"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
  eureka.instance.ip-address: "business-chat"
  HOSTNAME: "business-chat"
  PORT: "3002"
  EUREKA_HOST: "192.168.1.212"
  EUREKA_PORT: "8761"