apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-chat
  namespace: default
  labels:
    app: business-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-chat
  template:
    metadata:
      labels:
        app: business-chat
    spec:
      containers:
        - name: business-chat
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
              name: http
          envFrom:
            - configMapRef:
                name: business-chat-config
            - secretRef:
                name: business-chat-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3002
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:  
        - name: dockerhub-secret
