apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-chat
  namespace: default
  labels:
    app: business-chat
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: business-chat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: business-chat
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: business-chat
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          envFrom:
            - configMapRef:
                name: business-chat-config
            - secretRef:
                name: business-chat-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          # Give the app time to bind the port
          startupProbe:
            tcpSocket:
              port: 3002
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60   # ~5 minutes max warmup
          # Use TCP to avoid 401 on secured actuator; switch to HTTP if health is open
          readinessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

