apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: business-chat-pdb
  labels:
    app: business-chat
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: business-chat
