apiVersion: v1
kind: Service
metadata:
  name: business-chat
  namespace: default
  labels:
    app: business-chat
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: business-chat
