apiVersion: v1
kind: Service
metadata:
  name: business-chat
  namespace: default
  labels:
    app: business-chat
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002  
      targetPort: 3002  
      protocol: TCP
  selector:
    app: business-chat