apiVersion: v1
kind: Service
metadata:
  name: angular-ads
  namespace: default
  labels:
    app: angular-ads
spec:
  type: ClusterIP
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app: angular-ads
