apiVersion: v1
kind: Service
metadata:
  name: angular-ads
  namespace: default
  labels:
    app: angular-ads
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082           
      targetPort: 8082      
      protocol: TCP
  selector:
    app: angular-ads