apiVersion: apps/v1
kind: Deployment
metadata:
  name: fazeal-business
  namespace: default
  labels:
    app: fazeal-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fazeal-business
  template:
    metadata:
      labels:
        app: fazeal-business
    spec:
      containers:
        - name: fazeal-business
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8006
              name: http
          env:
            - name: SERVICE_NAME
              value: "fazeal-business"
            - name: NAMESPACE
              value: "default"
            - name: PORT
              value: "8006"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          envFrom:
            - configMapRef:
                name: fazeal-business-config
            - secretRef:
                name: fazeal-business-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          imagePullSecrets:
            - name: dockerhub-secret
