apiVersion: v1
kind: Service
metadata:
  name: fazeal-business
  namespace: default
  labels:
    app: fazeal-business
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: fazeal-business
