apiVersion: v1
kind: Service
metadata:
  name: dataload-service
  namespace: default
  labels:
    app: dataload-service
spec:
  type: ClusterIP
  ports:
    - port: 8106
      targetPort: 8106
      protocol: TCP
      name: http
  selector:
    app: dataload-service
