apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: translation-service-pdb
  labels:
    app: translation-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: translation-service
