apiVersion: v1
kind: Secret
metadata:
  name: translation-service-secret
  namespace: default
  labels:
    app: translation-service
type: Opaque
data:
  SERVICE_NAME: dHJhbnNsYXRpb24tc2VydmljZQ==
  DB_USER: YWRtaW4=
  DB_PASSWORD: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
