apiVersion: v1
kind: Service
metadata:
  name: translation-service
  namespace: default
  labels:
    app: translation-service
spec:
  type: ClusterIP
  ports:
    - port: 8104
      targetPort: 8104
      protocol: TCP
      name: http
  selector:
    app: translation-service
