apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-service
  namespace: default
  labels:
    app: ads-service
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ads-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ads-service
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: ads-service
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DISCOVERY_URL
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: DISCOVERY_URL
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: spring.profiles.active
            - name: CONFIG_URL
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: CONFIG_URL
            - name: spring.batch.job.enabled
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: spring.batch.job.enabled
            - name: eureka.instance.ip-address
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: eureka.instance.ip-address
            - name: server.port
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: server.port
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ads-service-secret
                  key: REDIS_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ads-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ads-service-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ads-service-secret
                  key: JWT_SECRET
            - name: SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: ads-service-secret
                  key: SERVICE_NAME
            - name: user-notification-service-api.base
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: user-notification-service-api.base
            - name: album-api.base
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: album-api.base
            - name: fazeal-business-admin-service-api.base
              valueFrom:
                configMapKeyRef:
                  name: ads-service-config
                  key: fazeal-business-admin-service-api.base
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 180  # allow ample time for startup
            periodSeconds: 15
            failureThreshold: 6
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"