apiVersion: v1
kind: Service
metadata:
  name: ads-service
  namespace: default
  labels:
    app: ads-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: ads-service
