apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: default
  labels:
    app: customer-service
data:
  SERVICE_NAME: "customer-service"
  NAMESPACE: "default"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
