apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-service-pdb
  labels:
    app: customer-service
    component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: customer-service