apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: promotion-service-pdb
  labels:
    app: promotion-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: promotion-service
