apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: default
  labels:
    app: promotion-service
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: http
  selector:
    app: promotion-service
