---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  namespace: default
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi