---
apiVersion: v1
kind: Secret
metadata:
  name: dataload-service-secrets
type: Opaque
data:
  DB_USER: "{{ dataload_db_user | b64encode }}"
  DB_PASSWORD: "{{ dataload_db_password | b64encode }}"
  WASABI_ACCESS_KEY: "{{ aws_access_key | b64encode }}"
  WASABI_SECRET_KEY: "{{ aws_secret_key | b64encode }}"
  JWT_SECRET: "{{ jwt_secret | b64encode }}"
  SECRET_KEY: "{{ jwt_secret | b64encode }}"
  REDIS_PASSWORD: "{{ redis_password | b64encode }}"