---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataload-service
<<<<<<< Updated upstream
  namespace: default
=======
>>>>>>> Stashed changes
  labels:
    app: dataload-service
    component: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataload-service
      component: fastapi
  template:
    metadata:
      labels:
        app: dataload-service
        component: fastapi
    spec:
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
      containers:
        - name: dataload-service
          image: khsaleh889/familymicroservices:dataload-service-latest # Placeholder, should be a variable
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: dataload-service-config
            - secretRef:
                name: dataload-service-secrets
          volumeMounts:
            - name: uploads-storage
              mountPath: /data/uploads
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 25
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: dockerhub-secret