---
apiVersion: v1
kind: Service
metadata:
  name: dataload-service
  labels:
    app: dataload-service
    component: fastapi
spec:
  type: ClusterIP
  selector:
    app: dataload-service
    component: fastapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000