---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataload-service-celery-worker
  labels:
    app: dataload-service
    component: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataload-service
      component: celery-worker
  template:
    metadata:
      labels:
        app: dataload-service
        component: celery-worker
    spec:
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc
      containers:
        - name: celery-worker-container
          image: khsaleh889/familymicroservices:dataload-service-celery-latest # Placeholder, should be a variable
          imagePullPolicy: Always
          command: ["celery"]
          args:
            - "-A"
            - "app.tasks.celery_worker.celery_app"
            - "worker"
            - "-l"
            - "INFO"
          # pull in all keys from ConfigMap & Secret
          envFrom:
            - configMapRef:
                name: dataload-service-config
            - secretRef:
                name: dataload-service-secrets
          # then individual vars here
          env:
            - name: DISCOVERY_URL
              value: http://192.168.1.211:8761
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: CONFIG_URL
              value: http://config-server
          volumeMounts:
            - name: uploads-storage
              mountPath: /data/uploads
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      imagePullSecrets:
        - name: dockerhub-secret