apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: watermark-detection-pdb
  labels:
    app: watermark-detection
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: watermark-detection
