apiVersion: v1
kind: Secret
metadata:
  name: watermark-detection-secret
  namespace: default
  labels:
    app: watermark-detection
type: Opaque
data:
  SERVICE_NAME: d2F0ZXJtYXJrLWRldGVjdGlvbg==
  DB_HOST: MTkyLjE2OC4xLjIyNA==
  DB_PORT: NTQzMg==
  DB_NAME: d2F0ZXJtYXJrLWRldGVjdGlvbl9kYg==
  DB_USER: ZmF6ZWFsX3VzZXI=
  DB_PASSWORD: ZmF6ZWFsX3Bhc3N3b3JkXzIwMjQ=
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMjAyNA==
  JWT_SECRET: and0X3NlY3JldF9rZXlfZm9yX3dhdGVybWFyay1kZXRlY3Rpb25fMjAyNA==
  API_KEY: YXBpX2tleV93YXRlcm1hcmstZGV0ZWN0aW9uXzIwMjQ=
