apiVersion: v1
kind: Service
metadata:
  name: watermark-detection
  namespace: default
  labels:
    app: watermark-detection
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: watermark-detection
