---
# Staging Environment Cluster Definition
env: "stg"

# Kubernetes Cluster
kube_masters:
  - 192.168.2.110 # Placeholder
  - 192.168.2.111 # Placeholder
kube_workers:
  - 192.168.2.120 # Placeholder
  - 192.168.2.121 # Placeholder
  - 192.168.2.122 # Placeholder

# Service Endpoints
kafka_broker_ip: "192.168.2.225" # Placeholder
db_host: "192.168.2.213" # Placeholder
redis_host: "192.168.2.217" # Placeholder
eureka_ip: "192.168.2.212" # Placeholder
dataload_db_host: "192.168.2.213" # Placeholder

# Ingress
ingress_domain: "stg.fazeal.com"

# MicroK8s
microk8s_version: "1.28/stable"
