apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loyalty-service-pdb
  labels:
    app: loyalty-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: loyalty-service
