apiVersion: v1
kind: ConfigMap
metadata:
  name: album-service-config
  namespace: default
data:
  DISCOVERY_URL: "http://192.168.1.212:8761"
  DB_HOST: "192.168.1.213"
  spring.profiles.active: "dev"
  CONFIG_URL: "http://config-server"
  amazonProperties.endpointUrl: "https://s3.amazonaws.com"
  amazonProperties.bucketName: "fazeal-album"
  amazonProperties.assetsBucketName: "fazeal-album-assets"
  spring.batch.job.enabled: "false"
  eureka.instance.ip-address: "album-service"
  eureka.instance.prefer-ip-address: "true"
  server.port: "8081"
  spring.cloud.stream.kafka.binder.brokers: "192.168.1.225:29093,192.168.1.225:39093"
  spring.kafka.producer.bootstrap-servers: "192.168.1.225:29093,192.168.1.225:39093"
  spring.kafka.consumer.bootstrap-servers: "192.168.1.225:29093,192.168.1.225:39093"
  spring.kafka.bootstrap-servers: "192.168.1.225:29093,192.168.1.225:39093"
  fazeal-social-service-api.base: "http://social-service:80"
  REDIS_HOST: "192.168.1.217"
  REDIS_PORT: "6379"