apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: album-service-pdb
  namespace: default
  labels:
    app: album-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: album-service
