apiVersion: v1
kind: Service
metadata:
  name: album-service
  namespace: default
  labels:
    app: album-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: album-service