apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  labels:
    app: order-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: order-service
