apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: default
  labels:
    app: order-service
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
  amazonProperties.accessKey: "VTU1V2dCdlFTc3VuWGVNM3MwdWE0bHlRYWRFWjM0Wmd6MlVKU2FTKw=="
  amazonProperties.secretKey: "aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA=="
  AWS_ACCESS_KEY: "VTU1V2dCdlFTc3VuWGVNM3MwdWE0bHlRYWRFWjM0Wmd6MlVKU2FTKw=="
  AWS_SECRET_KEY: "aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA=="
  amazonProperties.assetsSecretKey: "aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA=="
  amazonProperties.assetsAccessKey: "VTU1V2dCdlFTc3VuWGVNM3MwdWE0bHlRYWRFWjM0Wmd6MlVKU2FTKw=="

