apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  namespace: default
  labels:
    app: search-service
data:
  SERVICE_NAME: "search-service"
  NAMESPACE: "default"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
