apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: default
  labels:
    app: search-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: search-service
