---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: default
  labels:
    app: inventory-service
data:
  SERVICE_NAME: "inventory-service"
  NAMESPACE: "default"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
  server.port: "80"

  # Discovery
  DISCOVERY_URL: "http://192.168.1.212:8761"
  CONFIG_URL: "http://config-server"
  eureka.instance.ip-address: "inventory-service"
  spring.batch.job.enabled: "false"
  spring.profiles.active: "dev"

  # Database
  DB_HOST: "192.168.1.213"
  DB_PORT: "5432"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://192.168.1.213:5432/inventory-management?currentSchema=public"

  # Redis
  REDIS_HOST: "192.168.1.217"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: default
  labels:
    app: inventory-service
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: inventory-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: inventory-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Waiting for ${DB_HOST}:${DB_PORT}...";
              until nc -z ${DB_HOST} ${DB_PORT}; do sleep 2; done;
              echo "Postgres is reachable.";
          env:
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: inventory-service-config, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { configMapKeyRef: { name: inventory-service-config, key: DB_PORT } }

      containers:
        - name: inventory-service
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          env:
            - { name: SERVICE_NAME, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: SERVICE_NAME } } }
            - { name: SPRING_DATASOURCE_URL, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: SPRING_DATASOURCE_URL } } }
            - { name: SPRING_DATASOURCE_USERNAME, valueFrom: { secretKeyRef: { name: inventory-service-secret, key: DB_USER } } }
            - { name: SPRING_DATASOURCE_PASSWORD, valueFrom: { secretKeyRef: { name: inventory-service-secret, key: DB_PASSWORD } } }
            - { name: REDIS_PASSWORD, valueFrom: { secretKeyRef: { name: inventory-service-secret, key: REDIS_PASSWORD } } }
            - { name: NAMESPACE, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: NAMESPACE } } }
            - { name: ENVIRONMENT, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: ENVIRONMENT } } }
            - { name: LOG_LEVEL, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: LOG_LEVEL } } }
            - { name: server.port, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: server.port } } }
            - { name: DISCOVERY_URL, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: DISCOVERY_URL } } }
            - { name: CONFIG_URL, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: CONFIG_URL } } }
            - { name: eureka.instance.ip-address, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: eureka.instance.ip-address } } }
            - { name: spring.batch.job.enabled, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: spring.batch.job.enabled } } }
            - { name: spring.profiles.active, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: spring.profiles.active } } }
            - { name: REDIS_HOST, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: REDIS_HOST } } }
            - { name: REDIS_PORT, valueFrom: { configMapKeyRef: { name: inventory-service-config, key: REDIS_PORT } } }

          startupProbe:
            tcpSocket: { port: 80 }
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          readinessProbe:
            tcpSocket: { port: 80 }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket: { port: 80 }
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-service-hpa
  namespace: default
  labels:
    app: inventory-service
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-service-pdb
  namespace: default
  labels:
    app: inventory-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: inventory-service
