apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-service-pdb
  labels:
    app: inventory-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: inventory-service
