apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: default
  labels:
    app: inventory-service
type: Opaque
data:
  SERVICE_NAME: aW52ZW50b3J5LXNlcnZpY2U=
  DB_USER: YWRtaW4=
  DB_PASSWORD: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
