apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: default
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 8093
      targetPort: 8093
      protocol: TCP
      name: http
  selector:
    app: inventory-service
