apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: default
  labels:
    app: payment-service
data:
  SERVICE_NAME: "payment-service"
  NAMESPACE: "default"
  ENVIRONMENT: "dev"
  LOG_LEVEL: "INFO"
