apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  labels:
    app: payment-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: payment-service
