apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - port: 8098
      targetPort: 8098
      protocol: TCP
      name: http
  selector:
    app: payment-service
