apiVersion: v1
kind: Service
metadata:
  name: angular-customer
  namespace: default
  labels:
    app: angular-customer
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: angular-customer
