---
version: "8.17.0"

# Connect Kibana to the Elasticsearch cluster.
elasticsearchHosts: "http://elasticsearch-master:9200"

# Set resource requests and limits.
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"