apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: site-management-service-pdb
  labels:
    app: site-management-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: site-management-service
