apiVersion: v1
kind: Service
metadata:
  name: site-management-service
  namespace: default
  labels:
    app: site-management-service
spec:
  type: ClusterIP
  ports:
    - port: 8103
      targetPort: 8103
      protocol: TCP
      name: http
  selector:
    app: site-management-service
