apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: posts-service-pdb
  labels:
    app: posts-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: posts-service
