apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: default
  labels:
    app: posts-service
spec:
  type: ClusterIP
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
      name: http
  selector:
    app: posts-service
