apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-customer-ssr
  namespace: default
  labels:
    app: angular-customer-ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-customer-ssr
  template:
    metadata:
      labels:
        app: angular-customer-ssr
    spec:
      containers:
        - name: angular-customer-ssr
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: SERVICE_NAME
              value: "angular-customer-ssr"
            - name: NAMESPACE
              value: "default"
            - name: PORT
              value: "8082"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          envFrom:
            - configMapRef:
                name: angular-customer-ssr-config
            - secretRef:
                name: angular-customer-ssr-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:  
        - name: dockerhub-secret
