apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: default
  labels:
    app: config-server
data:
  SERVICE_NAME: "config-server"
  NAMESPACE: "default"
  LOG_LEVEL: "INFO"
  DISCOVERY_URL: "http://192.168.1.212:8761"
  BUSINESS_MANGE_DB_HOST: "192.168.1.213"
  spring.profiles.active: "dev"
