apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
  labels:
    app: config-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: config-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: config-server
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
    spec:
      containers:
        - name: config-server
          image: cybersolutioncontainer/familymicroservices:$IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              name: config-server
              protocol: TCP
          env:
            - name: DISCOVERY_URL
              value: "http://192.168.1.212:8761"
            - name: BUSINESS_MANGE_DB_HOST
              value: "192.168.1.213"
            - name: spring.profiles.active
              value: "dev"
            - name: CONFIG_USER
              value: "Khsaleh2024"
            - name: CONFIG_PASS
              value: "ATBBsS3gExWYHwV4nWSjgAR3ypSW4FCC4191"
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 200
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockerhub-secret 
