apiVersion: v1
kind: Secret
metadata:
  name: config-server-secret
  namespace: default
  labels:
    app: config-server
type: Opaque
data:
  SERVICE_NAME: Y29uZmlnLXNlcnZlcg==
  CONFIG_USER: "S2hzYWxlaDIwMjQ="
  CONFIG_PASS: "QVRCQnNTM2dFeFdZSHdWNG5XU2pnQVIzeXBTVzRGQ0M0MTkx"

