apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
  labels:
    app: config-server
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: config-server
