apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shopping-service-pdb
  labels:
    app: shopping-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: shopping-service
