apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: default
  labels:
    app: shopping-service
spec:
  type: ClusterIP
  ports:
    - port: 8102
      targetPort: 8102
      protocol: TCP
      name: http
  selector:
    app: shopping-service
