apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-employees
  namespace: default
  labels:
    app: angular-employees
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: angular-employees
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: angular-employees
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: angular-employees
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8183
              protocol: TCP
          envFrom:
            - configMapRef:
                name: angular-employees-config
            - secretRef:
                name: angular-employees-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          # Wait for port to open (nginx warmup)
          startupProbe:
            tcpSocket:
              port: 8183
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8183
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8183
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3