apiVersion: v1
kind: Service
metadata:
  name: angular-employees
  namespace: default
  labels:
    app: angular-employees
spec:
  type: ClusterIP
  ports:
    - port: 4205
      targetPort: 4205
      protocol: TCP
      name: http
  selector:
    app: angular-employees
