apiVersion: v1
kind: Service
metadata:
  name: angular-employees
  namespace: default
  labels:
    app: angular-employees
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8183
      protocol: TCP
      name: http
  selector:
    app: angular-employees
