apiVersion: v1
kind: Service
metadata:
  name: angular-employees
  namespace: default
  labels:
    app: angular-employees
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8183    
      targetPort: 8183  
      protocol: TCP
  selector:
    app: angular-employees