---
- name: Create a temporary directory for manifests
  tempfile:
    state: directory
    suffix: "{{ app_name }}"
  register: manifest_dir
  delegate_to: localhost
  run_once: yes

- name: Generate Kubernetes manifests from templates
  template:
    src: "{{ manifest_file }}.j2"
    dest: "{{ manifest_dir.path }}/{{ manifest_file }}"
  delegate_to: localhost
  run_once: yes
  loop:
    - configmap.yml
    - secret.yml
    - deployment.yml
    - service.yml
    - hpa.yml
    - ingress.yml
  loop_control:
    loop_var: manifest_file
  when: manifest_file in enabled_manifests

- name: Apply the generated manifests to the cluster
  k8s:
    state: present
    src: "{{ manifest_dir.path }}/{{ manifest_file }}"
    kubeconfig: "~/.kube/config" # This should point to the microk8s config
  delegate_to: localhost
  run_once: yes
  loop:
    - configmap.yml
    - secret.yml
    - deployment.yml
    - service.yml
    - hpa.yml
    - ingress.yml
  loop_control:
    loop_var: manifest_file
  when: manifest_file in enabled_manifests

- name: Clean up temporary manifest directory
  file:
    path: "{{ manifest_dir.path }}"
    state: absent
  delegate_to: localhost
  run_once: yes