---
- name: Map app variables to template variables
  set_fact:
    app_name: "{{ app.name }}"
    app_namespace: "{{ app.namespace | default('default') }}"
    app_image: "{{ app.image_repo | default('khsaleh889/angularmicroservices') }}:{{ app.image_tag }}"
    app_replicas: "{{ app.replicas | default(1) }}"
    app_container_port: "{{ app.container_port | default(80) }}"
    app_resources: "{{ app.resources | default({'requests': {'cpu': '100m', 'memory': '128Mi'}, 'limits': {'cpu': '500m', 'memory': '512Mi'}}) }}"
    app_image_pull_secrets: "{{ app.image_pull_secrets | default([]) }}"
    app_health_check_type: "{{ app.health_check_type | default('httpGet') }}"
    app_health_check_path: "{{ app.health_check_path | default('/') }}"
    app_config: "{{ app.config | default({}) }}"
    app_secrets: "{{ app.secrets | default({}) }}"
    app_hpa: "{{ app.hpa | default({'min_replicas': 2, 'max_replicas': 10, 'cpu_utilization': 70, 'memory_utilization': 70}) }}"
    app_ingress_hostname: "{{ app.ingress_hostname | default(app.name + '.local') }}"
    enabled_manifests: "{{ app.enabled_manifests | default(['configmap.yml', 'secret.yml', 'deployment.yml', 'service.yml', 'hpa.yml', 'ingress.yml']) }}"
    use_refactored_config: "{{ use_refactored_config | default(false) }}"

# Service-specific configuration is now handled directly in templates

- name: Create a temporary directory for manifests
  tempfile:
    state: directory
    suffix: "{{ app_name }}"
  register: manifest_dir
  delegate_to: localhost
  run_once: true

- name: Generate Kubernetes manifests from templates
  template:
    src: "{{ manifest_file }}.j2"
    dest: "{{ manifest_dir.path }}/{{ manifest_file }}"
  delegate_to: localhost
  run_once: true
  loop:
    - configmap.yml
    - secret.yml
    - deployment.yml
    - service.yml
    - hpa.yml
    - ingress.yml
  loop_control:
    loop_var: manifest_file
  when: manifest_file in enabled_manifests

- name: Apply the generated manifests to the cluster
  k8s:
    state: present
    src: "{{ manifest_dir.path }}/{{ manifest_file }}"
    kubeconfig: "~/.kube/config"
  delegate_to: localhost
  run_once: true
  loop:
    - configmap.yml
    - secret.yml
    - deployment.yml
    - service.yml
    - hpa.yml
    - ingress.yml
  loop_control:
    loop_var: manifest_file
  when: manifest_file in enabled_manifests

- name: Create base64 encoded secret data
  set_fact:
    secret_data: "{{ {} }}"
  when: use_refactored_config and service_configs[app_name] is defined and service_configs[app_name].secret is defined

- name: Build secret data with base64 encoding
  set_fact:
    secret_data: "{{ secret_data | combine({item.key: item.value | b64encode}) }}"
  loop: "{{ service_configs[app_name].secret | default({}) | dict2items(key_name='key', value_name='value') }}"
  when: use_refactored_config and service_configs[app_name] is defined and service_configs[app_name].secret is defined

- name: Patch ConfigMap with service-specific configuration
  shell: |
    kubectl patch configmap {{ app_name }}-config -p '{"data":{{ service_configs[app_name].configmap | to_json }}}' --type='merge'
  delegate_to: localhost
  run_once: true
  when: use_refactored_config and service_configs[app_name] is defined and service_configs[app_name].configmap is defined

- name: Patch Secret with service-specific configuration
  shell: |
    kubectl patch secret {{ app_name }}-secret -p '{"data":{{ secret_data | to_json }}}' --type='merge'
  delegate_to: localhost
  run_once: true
  when: use_refactored_config and service_configs[app_name] is defined and service_configs[app_name].secret is defined and secret_data is defined

- name: Clean up temporary manifest directory
  file:
    path: "{{ manifest_dir.path }}"
    state: absent
  delegate_to: localhost
  run_once: true