apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-server-pdb
  labels:
    app: api-server
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: api-server
