apiVersion: v1
kind: Secret
metadata:
  name: api-server-secret
  namespace: default
  labels:
    app: api-server
type: Opaque
data:
  SERVICE_NAME: YXBpLXNlcnZlcg==
  DB_USER: YWRtaW4=
  DB_PASS: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
  JWT_SECRET: and0X3NlY3JldF9rZXlfZm9yX2FwaS1zZXJ2ZXJfMjAyNA==
  amazonProperties.accessKey: "QUtJQTIyWjdRTFM2QkxWQjVIVkQ="
  amazonProperties.secretKey: "VTU1V2dCdlFTc3VuWGVNM3MwdWE0bHlRYWRFWjM0Wmd6MlVKU2FTKw=="
  AWS_ACCESS_KEY: "QUtJQTIyWjdRTFM2QkxWQjVIVkQ="
  
