apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: default
  labels:
    app: api-server
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: api-server
