apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-service-pdb
  namespace: default
  labels:
    app: catalog-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: catalog-service