apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: default
  labels:
    app: catalog-service
type: Opaque
data:
  SERVICE_NAME: Y2F0YWxvZy1zZXJ2aWNl
  DB_HOST: MTkyLjE2OC4xLjIyNA==
  DB_PORT: NTQzMg==
  DB_NAME: Y2F0YWxvZy1zZXJ2aWNlX2Ri
  DB_USER: YWRtaW4=
  DB_PASSWORD: bmV3MjAyNQ==
  REDIS_PASSWORD: YWRtaW4xMjM0
  JWT_SECRET: and0X3NlY3JldF9rZXlfZm9yX2NhdGFsb2ctc2VydmljZV8yMDI0
  API_KEY: YXBpX2tleV9jYXRhbG9nLXNlcnZpY2VfMjAyNA==
