apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: default
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: catalog-service