apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: default
  labels:
    app: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: SERVICE_NAME
              value: "chat-app"
            - name: NAMESPACE
              value: "default"
            - name: PORT
              value: "3000"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          envFrom:
            - configMapRef:
                name: chat-app-config
            - secretRef:
                name: chat-app-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          imagePullSecrets:
            - name: dockerhub-secret
