apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chat-app-pdb
  namespace: default
  labels:
    app: chat-app
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: chat-app