apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: default
  labels:
    app: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: khsaleh889/familymicroservices:$IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8097
              name: http
          env:
            - name: SERVICE_NAME
              value: "payment-gateway"
            - name: NAMESPACE
              value: "default"
            - name: PORT
              value: "8097"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          envFrom:
            - configMapRef:
                name: payment-gateway-config
            - secretRef:
                name: payment-gateway-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8097  
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8097  
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: dockerhub-secret
