apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-gateway-pdb
  labels:
    app: payment-gateway
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: payment-gateway
