apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
  namespace: default
  labels:
    app: payment-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8097
      targetPort: 8097
      protocol: TCP
      name: http
  selector:
    app: payment-gateway
