apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: employees-service-pdb
  namespace: default
  labels:
    app: employees-service
    component: pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: employees-service