apiVersion: v1
kind: Secret
metadata:
  name: employees-service-secret
  namespace: default
  labels:
    app: employees-service
type: Opaque
data:
  SERVICE_NAME: ZW1wbG95ZWVzLXNlcnZpY2U=
  DB_HOST: MTkyLjE2OC4xLjIyNA==
  DB_PORT: NTQzMg==
  DB_NAME: ZW1wbG95ZWVzLXNlcnZpY2VfZGI=
  DB_USER: ZmF6ZWFsX3VzZXI=
  DB_PASSWORD: ZmF6ZWFsX3Bhc3N3b3JkXzIwMjQ=
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMjAyNA==
  JWT_SECRET: and0X3NlY3JldF9rZXlfZm9yX2VtcGxveWVlcy1zZXJ2aWNlXzIwMjQ=
  API_KEY: YXBpX2tleV9lbXBsb3llZXMtc2VydmljZV8yMDI0
