apiVersion: v1
kind: Secret
metadata:
  name: employees-service-secret
  namespace: default
  labels:
    app: employees-service
type: Opaque
data:
  DB_USER: YWRtaW4=                       
  DB_PASSWORD: YWRtaW4xMjM0                
  REDIS_PASSWORD: YWRtaW4xMjM0           
  amazonProperties.accessKey: VVU1MUJSWVFSOEpKSkQyWDBTMTE=   
  amazonProperties.secretKey: aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA== 
  AWS_ACCESS_KEY: VVU1MUJSWVFSOEpKSkQyWDBTMTE=                
  AWS_SECRET_KEY: aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA==            
  amazonProperties.assetsSecretKey: aXMzYTNSZWtUYlFIdHNFQTAydFVBYW40Q3pIU3VpQTdodFA2a2xScA== 
  amazonProperties.assetsAccessKey: VVU1MUJSWVFSOEpKSkQyWDBTMTE=   
