apiVersion: v1
kind: Service
metadata:
  name: employees-service
  namespace: default
  labels:
    app: employees-service
spec:
  type: ClusterIP
  selector:
    app: employees-service
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      protocol: TCP